main/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from main import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView



urlpatterns = [

    path('', views.index, name="home"),
    path('signup/', views.signup, name='signup'),
    path('enroll/', views.etant_eleve, name='etant-eleve'),
     path('about/', views.about_us_view, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/settings/', views.Settings.as_view(), name="settings"),
    path('account/settings/password-change/', PasswordChangeView.as_view(template_name='main/password_change.html', success_url=reverse_lazy('password-change-done')), name='password-change'),
    path('account/settings/passord-change-done/', PasswordChangeDoneView.as_view(template_name='main/password_change_done.html'), name='password-change-done'),
    path('user/profile/<str:username>', views.user_profile, name="user-profile"),
    path('user-profile-photo-full/<str:username>', views.user_photo_full, name="user-photo-full"),
]

sciexpo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField

class About(models.Model):
    content = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to = 'images/ABOUT_US', null=True)

    def __str__(self):
        return str(self.id)+" A PROPOS DE NOUS"

    class Meta:
        verbose_name = "À propos de nous"


class Ecole(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom


class Inscrit(AbstractUser):
    class FunctionInSchool(models.TextChoices):
        ELEVE = 'Eleve', _('Elève')
        PROFESSOR = 'Professeur', _('Professeur')
        DIRECTEUR = 'Directeur', _('Directeur')
        PREFET = 'Prefet', _('Préfet')
        SECRETAIRE = 'Secretaire', _('Secretaire')
        ANCIEN_ELEVE = 'Ancien_eleve', _('Ancien élève')
        DEFAULT = '-', _('-')

    function_in_school = models.CharField(
        max_length=40,
        choices=FunctionInSchool.choices,
        default=FunctionInSchool.DEFAULT,
        verbose_name='Statut'
    )

    school_name = models.ForeignKey(Ecole, on_delete=models.SET_NULL, null=True)

    current_city = models.CharField(max_length=20, null=True, verbose_name="Ville ou territoire actuel(le)")

    birth_date = models.DateField(null=True, verbose_name="Date de naissance")

    about = models.TextField(null=True, blank=True, verbose_name="A propos de vous")

    photo = models.ImageField(upload_to = 'photos', default='photos/default.jpg')

    cover_image = models.ImageField(upload_to = 'images',
                                    default='images/default_img/cover_default.jpg',
                                   verbose_name="Image de couverture")



class Option(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom


class EtantEleve(models.Model):
    eleve = models.OneToOneField(Inscrit, on_delete=models.CASCADE)
    class ClasseEleve(models.TextChoices):
        SEPTIEME = '7emeEB', _('7e EB')
        HUITIEME = '8emeEB', _('8e EB')
        PREMIERE = '1ere', _('1ère des Humanités')
        DEUXIEME = '2eme', _('2ème des Humanités')
        TROISIEME = '3eme', _('3ème des Humanités')
        QUATRIEME = '4eme', _('4ème des Humanités')
        DEFAULT = '-', _('-')

    classe_del_eleve = models.CharField(
        max_length=30,
        choices=ClasseEleve.choices,
        default=ClasseEleve.DEFAULT,
        verbose_name="classe de l'élève")

    option = models.ForeignKey(
        Option, on_delete=models.CASCADE, null=True, blank=True)

    tuteur = models.CharField(max_length=30)

    def __str__(self):
        return self.eleve.first_name+" "+self.eleve.last_name+", "+self.eleve.school_name.nom


    class Meta:
        verbose_name = "Élève"

main/forms.py
from django import forms
from main.models import Inscrit, EtantEleve
from django.utils.translation import gettext_lazy as _


class InscritForm(forms.ModelForm):

    class Meta:
        model = Inscrit

        fields = ['username', 'first_name', 'last_name', 'email', 'school_name',
                  'current_city', 'birth_date', 'function_in_school', 'about', 'password']

        widgets = {

            'username': forms.TextInput(attrs={'class': 'form-control'}),

            'first_name': forms.TextInput(attrs={'class': 'form-control'}),

            'last_name': forms.TextInput(attrs={'class': 'form-control'}),

            'email': forms.TextInput(attrs={'class': 'form-control', 'type': 'email'}),

            'school_name': forms.Select(attrs={'class': 'form-control'}),

            'birth_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),

            'about': forms.Textarea(attrs={'class': 'form-control', 'cols': 20, 'rows': 4, 'placeholder': "Ex: CEO de Turing, Docteur en TIC, ..."}),

            'password': forms.PasswordInput(attrs={'class': 'form-control'}),

        }

        labels = {
            "username": _("Nom d'utilisateur"),
            "first_name": _("Prénom"),
            "last_name": _("Nom"),
            "email": _("Adresse email"),
            "password": _("Mot de passe"),

        }


class EtantEleveForm(forms.ModelForm):

    class Meta:
        model = EtantEleve

        fields = ['eleve', 'classe_del_eleve', 'option', 'tuteur']

        labels = {

            "classe_del_eleve": _("Classe"),
            "tuteur": _("Nom du responsable"),

        }


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label="Nom d'utilisateur",
                               widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=100, label="Mot de passe",
                               widget=forms.PasswordInput(attrs={"class": "form-control"}))


class SettingsForm(forms.ModelForm):

    class Meta:
        model = Inscrit

        fields = ['first_name', 'last_name', 'email', 'school_name', 'current_city',
                  'birth_date', 'function_in_school', 'about', 'photo', 'cover_image']

        widgets = {

            'first_name': forms.TextInput(attrs={'class': 'form-control'}),

            'last_name': forms.TextInput(attrs={'class': 'form-control'}),

            'email': forms.TextInput(attrs={'class': 'form-control'}),

            'birth_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),

            'about': forms.Textarea(attrs={
              'class': 'form-control',
              'placeholder': "Ex: Je suis un passioné de la Tech, PDG de Mulykap, Master en Economie, ...", 'cols': 20, 'rows': 4}),
        }

main/views.py
from django.shortcuts import render, redirect
from main.forms import InscritForm, EtantEleveForm, LoginForm, SettingsForm
from articles.models import Article
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.core.paginator import Paginator
from .models import About, Inscrit
from django.views import View
from django.contrib import messages

User = get_user_model()

# Create your views here.

def index(request):
  if not request.user.is_authenticated:
    return redirect("login")

  articles = Article.objects.all().order_by('-pub_date')
  #top_article = articles.first()

  page = Paginator(articles, 3)
  pagenumber = request.GET.get('page')
  thispage = page.get_page(pagenumber)

  return render(request, 'main/index.html', {"page": thispage})

def about_us_view(request):
    about = About.objects.get(pk = 1)
    return render(request, 'main/about_us.html', {"about_us": about})
def signup(request):
  form = InscritForm()
  if request.method == "POST":
    f = InscritForm(request.POST)
    if f.is_valid():
      username = f.cleaned_data['username']
      first_name = f.cleaned_data['first_name']
      last_name = f.cleaned_data['last_name']
      email = f.cleaned_data['email']
      current_city = f.cleaned_data['current_city']
      birth_date = f.cleaned_data['birth_date']
      function_in_school = f.cleaned_data['function_in_school']
      password = f.cleaned_data['password']
      school_name = f.cleaned_data['school_name']

      user = User.objects.create_user(
          username = username,
          first_name = first_name,
          last_name = last_name,
          email = email,
          current_city = current_city,
          birth_date = birth_date,
          password = password,
          school_name = school_name,
          function_in_school = function_in_school

      )
      if function_in_school == "Eleve":
            form = EtantEleveForm()
            return render(request, 'main/etant_eleve.html', {"form":form, "eleve":user})
      login_form = LoginForm()
      return render(request, 'main/login.html', {'msg':f'{first_name}, votre compte a été créé avec succès !', 'form':login_form})

    return render(request, 'main/signup.html')

  return render(request, 'main/signup.html', {'form':form})

def etant_eleve(request):
    if request.method == "POST":
        form = EtantEleveForm(request.POST)
        eleve = request.POST["eleve"]
        user = User.objects.get(pk=int(eleve))
        if form.is_valid():
            form.save()
            return render(request, 'main/login.html', {'msg':f'{user.first_name}, votre compte a été créé avec succès!', 'form':LoginForm()})
        else:
            render(request, 'main/etant_eleve.html', {"form":form, 'eleve':user})
class LoginView(View):
    form = LoginForm()
    def get(self,request, *args, **kwargs):
        return render(request, 'main/login.html', {"form":self.form})

    def post(self, request, *args, **kwargs):
        f = LoginForm(request.POST)
        if f.is_valid():
            user = authenticate(username=f.cleaned_data['username'], password=f.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect("home")
            return render(request, "main/login.html", {"form":f, "error":"Nom d'utilisateur ou mot de passe incorrects!"})
        return redirect("login")

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect("login")
    return redirect("login")


class Settings(View):

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
        	return redirect("login")
        form = SettingsForm(instance=request.user)
        return render(request, "main/settings.html", {"form":form})

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
        	return redirect("login")
        form = SettingsForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Modifications enregistrées avec succès!")
            return redirect("settings")
        return redirect("settings")


def user_profile(request, username):
    try:
        user = Inscrit.objects.get(username=username)
    except KeyError:
        return redirect("home")
    articles = Article.objects.filter(author = user)
    context = {
               "username":user.get_username(),
               "cover_image":user.cover_image.url,
               "photo": user.photo.url,
               "first_name": user.first_name,
               "last_name":user.last_name,
               "statut": user.function_in_school,
               "ecole": user.school_name,
               "about":user.about,
               "articles": articles,
              }

    return render(request, 'main/user_profile.html', context)



def user_photo_full(request, username):
    try:
        user = Inscrit.objects.get(username=username)
    except KeyError:
        return redirect("home")
    context = {
               "username":user.get_username(),
               "photo": user.photo.url,
               "first_name": user.first_name,
               "last_name":user.last_name,
              }

    return render(request, 'main/user_photo_full.html', context)

main/templates/main/about_us.html
{% extends 'base_template.html' %}

{% block title %} A propos {% endblock %}

{% block content %}
<div class="container">

  <div class="about-us-div container">
    <div class="p-4">
      {% autoescape off %}
      {{ about_us.content }}
      {% endautoescape %}
    </div>

  </div>
<br>
</div>

{% endblock %}

main/templates/main/etant_eleve.html
{% extends 'base_template.html' %}

{% block title %}Inscription  élève{% endblock %}

{% block content %}
<div class="container">

<div class="enroll-div container col-12">

  <h3>
    Terminer l'inscription
  </h3>

    <fieldset>
      <form action="{% url 'etant-eleve' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
 {% if form %}
                <input type="hidden" name="eleve" value="{{eleve.id}}" />
                <div>
                    Classe de l'élève:
                </div>

                <div>
                    {{form.classe_del_eleve}}
                </div>
                <br>

                <div>
                    Option:
                </div>

                <div>
                    {{form.option}}
                </div>
                <br>


                <div>
                Nom du responsable
          		</div>
                <div>
                    {{form.tuteur}}
                </div>

                <br>

        <br>
        <div>
          <input class="btn btn-primary" type="submit" value="Terminer" />
        </div>
{% endif %}
      </form>
    </fieldset>

</div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'base_template.html' %}

{% block title %}{% endblock %}

{% block content %}
<section class="home-section col-sm-12">

    <div class="home">

        <h3 class="text-success">
            {{ msg }}
        </h3>

    {% if user.is_authenticated %}

    <h4>
        <a href="{% url 'create-article' %}">Créer un article</a>
    </h4>

    {% endif %}

    {% if page %}
    <div class="articles p-4 row">

        {% for article in page %}

        {% autoescape off %}

        <div class="article p-2">
            <a href="{% url 'article-details' article.slug %}">
                <div class="image">
                    <img src="{{ article.photo.url }}" alt="photo" />
                </div>
                <span class="categorie">{{article.categorie}}</span><br>
                <b>{{article.title}}</b><br>
                {{ article.excerpt|truncatewords:15 }}
            </a>
        </div>

        {% endautoescape %}
        {% endfor %}

    </div>

    {% endif %}

    <div class="pagination">

        <div class="pagin-cover">
            <center>
                {% if page.has_previous %}
                <div>
                    <button class="btn btn-secondary">
                        <a href="{% url 'home' %}?page={{ page.previous_page_number }}"> Précédent </a></button>
                </div>
                {% endif %}

                {% if page.has_next %}
                <div>
                    <button class="btn btn-secondary">
                        <a href="{% url 'home' %}?page={{ page.next_page_number }}">Suivant  >> </a>
                    </button>
                </div>

                {% endif %}

            </center>
        </div>

    </div>
     </div>

</section>

{% endblock %}

{% block aside %}

<aside class="aside"> À voir aussi... </aside>

{% endblock %}

main/templates/main/login.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}Connexion{% endblock %}

{% block content %}
<div class="container">

    <div class="login-div container col-12">
        <h4 class="text-success">
            {{msg}}
        </h4>
        <h3>
            Connectez-vous
        </h3>
        <span class="text-danger">{{error}}</span>
        <fieldset>
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}

                {% if form %}
                <div>
                    {{form.username.label}}
                </div>
                <div class="username-div">
                    {{form.username}}
                </div>
                <br>
                <div>
                    {{ form.password.label}}
                </div>
                <div class="password-div">
                    {{ form.password}}

                        <a class="eye" href="#!">
                         <img class="eye-image" src="/media/icons/visibility.png" />
                        </a>

                </div><br>

                {% endif %}
                <br>
                <div>
                    <input class="btn btn-primary" type="submit" value="Se connecter" />
                </div>
            </form>
        </fieldset> <br>
        <span>Besoin d'un compte? <a href="{% url 'signup' %}"><b>Inscrivez-vous</b></a></span>
        <br>
    </div>
</div>
{% endblock %}

main/templates/main/password_change.html
{% extends 'base_template.html' %}

{% block title %} Modification du mot de passe {% endblock %}

{% block content %}
<div class="container">

    <div class="settings-div container">

        {% if user.is_authenticated %}

        {% if msm %}
        <span>{{msm}}</span>
        {% endif %}

        <h4>Modifiez votre mot de passe </h4>

        <fieldset>
            <form enctype="multipart/form-data" method="POST"
                action="{% url 'password-change' %}">

                {% csrf_token %}

                <div class="settings-password-div">
                    {% for error in form.non_field_errors %}
                    <div class="text-danger">
                        {{error}}
                    </div>
                    {% endfor %}

                    {% for field in form %}
                    <div>{{field.label}}</div>
                    <div>
                        {{field}}
                    </div>

                    {% if field.errors %}
                    <div class="text-danger">
                        {{field.errors}}
                    </div>
                    {% endif %}

                    {% endfor %}

                    <div>

                    </div> <br>

                    <button type="submit" class="btn btn-primary w-100"> Changer
                        le mot de passe </button>
                </div>
            </form>

        </fieldset>
        {% endif %}

        <br>
        {% if not user.is_authenticated %}

        <h3> Vous devez vous <a href="{% url 'login' %}">connecter</a> pour
            pouvoir modifier votre compte! </h3>

        {% endif %}

    </div>
</div>
{% endblock %}

main/templates/main/password_change_done.html
{% extends 'base_template.html' %}

{% block title %}  Mot de passe modifié{% endblock %}

{% block content %}

<div class="container">



    {% if user.is_authenticated %}

    {% if msm %}
    <span class="text-success">{{msm}}</span>
    {% endif %}

    <h2>Mot de passe modifié avec succès </h2>

    {% endif %}

    <br>
    {% if not user.is_authenticated %}

    <h3> Vous devez vous connecter pour pouvoir modifier votre compte! </h3>

    {% endif %}


</div>
{% endblock %}

main/templates/main/settings.html
{% extends 'base_template.html' %}

{% block title %}Paramètres{% endblock %}

{% block content %}
<div class="container">

    <div class="settings-div col-12 container">

        {% if messages %}
        {% for message in messages %}
        <h4 class="text-success">
            {{ message }}
        </h4>
        {% endfor %}
        {% endif %}

        <fieldset>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                Nom d'utilisateur: {{ user.username }}
                {% for field in form %}



                <br>
                {% if field.label == 'Photo' %}
                <div>
                    Photo de profil: <br>
                    <img src="{{user.photo.url}}" id="user-photo" class="user-image" />
                   <label class="photo-label">
                       <input class="w-25" type="file" accept="image/*" name="photo" id="id_photo" />
                       <span>Choisir une image</span>
                   </label>
                   </div>
                {% elif field.label == 'Image de couverture' %}
                <div>
                    Photo de couverture:<br>
                    <img src="{{user.cover_image.url}}" id="user-cover-image" class="user-image" />
                  <label class="cover-image-label">
                      <input class="w-25"  type="file" accept="image/*" name="cover_image" id="id_cover_image" />
                  <span>Choisir une image</span>
                    </label>
                  </div>

                {% else %}
                <div>
                    <label>{{ field.label }}</label>
                </div>

                <div>{{field}}</div>
                {% endif %}

                {% endfor %}
                <br>
                <div class="container">
                    <button class="btn btn-primary w-50" type="submit">Enregistrer</button>
                </div>

            </form>
        </fieldset>
        <hr>
        <div class="p-4 m-2">
            <a href="{% url 'password-change' %}"><b>Changer le mot de passe</b></a>
        </div>
    </div>
    <br>
</div>
{% endblock %}

main/templates/main/signup.html
{% extends 'base_template.html' %}

{% block title %}Inscription{% endblock %}


{% block content %}
<div class="container">

<div class="signup-div col-12 container">
    <h3>
      Créez votre compte maintenant
    </h3>
    <span class="text-danger">{{error}}</span>
    <fieldset>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form %}

        <div>
            <br>
            <label>{{ field.label }}</label>
        </div>
         {% if field.name == 'password' %}
         <div class="password-div">
             {{field}}
             <a class="eye" href="#!">
             <img class="eye-image" src="/media/icons/visibility.png" />
             </a>
          </div>
          {% else %}
          <div> {{field}}</div>
          {% endif %}
        {% endfor %}
        <br>
        <div class="container">

            <button class="btn btn-primary w-50" type="submit">S'inscrire</button>
        </div>

      </form>
    </fieldset>

</div>

</div>

{% endblock %}

main/templates/main/user_photo_full.html
{% extends 'base_template.html' %}

{% block title %} Photo de profil {% endblock %}

{% block content %}
<div class="container">

  <div class="container w-100">

   <img class="w-100" src="{{ photo }}" >

  </div>
<br>
</div>

{% endblock %}

main/templates/main/user_profile.html
{% extends 'base_template.html' %}

{% block title %} {{ first_name }} {{ last_name }} {% endblock %}


{% block content %}
<div class="user-profile p-2">
    <div class="profile-div p-1">
        <div>
          <a href="{% url 'user-photo-full' username %}">
           <div class="cover-image w-100 pt-4 pl-1 pb-1" style="background: url({{cover_image}})">
            <a href="{% url 'user-photo-full' username %}"> <img class="profile-photo" src="{{ photo }}" /> </a><br>

           </div>
          </a>
            <h4>{{ first_name }} {{ last_name }}</h4>
            <span><i>{{ statut }} chez </i><b>{{ ecole }} </b></span>
        </div>
        <div>
            <b><i></i></b>
            {% if about %}
            <div class="">
                {{ about }}
            </div>
            {% endif %}
        </div>
    </div>
    <br>
    <hr class="100%">
    <h4>
        Ses récents articles
    </h4>
    <div class="">
        <div class="articles">
            {% if articles %}
            {% for article in articles %}
            <div class="article p-2">
                <a href="{% url 'article-details' article.slug %}" >
                    <div>
                        <img class="w-100" src="{{ article.photo.url }}" />
                    </div>
                    <span class="categorie">{{chaquearticle.categorie}}</span><br>
                    <b>{{article.title}}</b>
                    <br>
                    {{ article.excerpt|truncatewords:20 }}
                </a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}